epoch: 0 loss: 1.5189878 LR: [0.01] step: 357 score: 10 best_score: 10
Traceback (most recent call last):
  File "c:\Users\Talmid\Downloads\Breakout\Breakout (1)\Breakout\DQN_trainer.py", line 152, in <module>
    main ()
  File "c:\Users\Talmid\Downloads\Breakout\Breakout (1)\Breakout\DQN_trainer.py", line 130, in main
    wandb.log(loss.item)
  File "C:\Users\Talmid\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 449, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Talmid\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Talmid\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Talmid\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 1873, in log
    self._log(data=data, step=step, commit=commit)
  File "C:\Users\Talmid\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 1582, in _log
    raise ValueError("wandb.log must be passed a dictionary")
ValueError: wandb.log must be passed a dictionary
